version: '3.8'

services:
  mysql5.6:
    image: mysql:5.6
    environment:
      MYSQL_DATABASE: test_performance
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    deploy:
      resources:
        limits:
          cpus:  '1'
          memory: 512M
        reservations:
          cpus:  '1'
          memory: 512M

  ruby:
    image: ruby:3
    environment:
      MYSQL_DATABASE: test_performance
    volumes:
      - ./script.rb:/root/script.rb
    command: sleep INF
    depends_on:
      - mysql5.6
